version: '3.8'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  backend:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - redis
